### ISSUE TITLE
Drop SNAP

### ISSUE THREAD

**Issue by ghost** [maccmu/macposts#30]
It has been planned for long, so let us discuss this issue.

The biggest problem with SNAP is that it bundles an alternative template library, glib, which makes `libmacposts` unnecessarily complicated, and may also bring some portability issues. Also, I suspect our MSVC builds failed due to SNAP.

Besides, it seems [SNAP is no longer actively maintained](https://github.com/snap-stanford/snap). It has some issues too so we have to use a [forked version of it](https://github.com/maccmu/snap), which nobody seems willing to maintain.

So we would like to drop SNAP completely. Things to do:

- [x] Roll our own graph library. (#37) ~~Find a data structure for graphs. One option is to roll our own, which is not hard currently -- an adjacency list is enough. The other option is to use [igraph](https://github.com/igraph/igraph), with which I had some good experience a few years ago. With igraph, we can save the effort to implement common graph algorithms, but currently we do not have much need for that, so this reason itself may not justify the burden of adding and tracking a new dependency.~~
- [x] Use the new graph library. (#50)
- [x] Convert all glib data types to C++ native data types. For example, `TInt` to `int` or `long`. (#55)
- [x] Replace glib functions with functions in the C++ standard library. (#55)
- [x] Drop the SNAP submodule completely. (#55)

**Comment by ghost** [comment]
Related: #29.

**Comment by psychogeekir** [comment]
I started to use C++ native data types and functions. Probably we can get this issue solved before starting working on #29. About the graphs, perhaps we can create our own graph class to replace the graph in SNAP. Do you have time to do that recently? Or I can also work on it after I wrapped up a few tasks on hand.

**Comment by ghost** [comment]
> Do you have time to do that recently?

I actually don't. Maybe I will work on it in a few weeks.
